# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/aarav/Documents/QtWorkspace/add_shipper.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddShipper(object):
    def setupUi(self, AddShipper):
        AddShipper.setObjectName("AddShipper")
        AddShipper.resize(800, 600)
        AddShipper.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(AddShipper)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 10, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.listViewShippers = QtWidgets.QListView(self.centralwidget)
        self.listViewShippers.setGeometry(QtCore.QRect(40, 80, 261, 451))
        self.listViewShippers.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.listViewShippers.setObjectName("listViewShippers")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(320, 80, 451, 441))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineEditShipperName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditShipperName.setGeometry(QtCore.QRect(10, 30, 441, 21))
        self.lineEditShipperName.setObjectName("lineEditShipperName")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.label_3.setObjectName("label_3")
        self.textEditShipperAddress = QtWidgets.QTextEdit(self.groupBox)
        self.textEditShipperAddress.setGeometry(QtCore.QRect(10, 80, 441, 51))
        self.textEditShipperAddress.setObjectName("textEditShipperAddress")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 111, 16))
        self.label_4.setObjectName("label_4")
        self.textEditOriginAddress = QtWidgets.QTextEdit(self.groupBox)
        self.textEditOriginAddress.setGeometry(QtCore.QRect(10, 160, 441, 51))
        self.textEditOriginAddress.setObjectName("textEditOriginAddress")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 220, 141, 16))
        self.label_5.setObjectName("label_5")
        self.textEditDestinationAddress = QtWidgets.QTextEdit(self.groupBox)
        self.textEditDestinationAddress.setGeometry(QtCore.QRect(10, 240, 441, 51))
        self.textEditDestinationAddress.setObjectName("textEditDestinationAddress")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 300, 141, 16))
        self.label_6.setObjectName("label_6")
        self.textEditComments = QtWidgets.QTextEdit(self.groupBox)
        self.textEditComments.setGeometry(QtCore.QRect(10, 320, 441, 71))
        self.textEditComments.setObjectName("textEditComments")
        self.pushButtonAddShipper = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonAddShipper.setGeometry(QtCore.QRect(330, 400, 114, 32))
        self.pushButtonAddShipper.setStyleSheet("background-color: rgb(40, 195, 50);")
        self.pushButtonAddShipper.setObjectName("pushButtonAddShipper")
        self.pushButtonEditShipper = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonEditShipper.setGeometry(QtCore.QRect(210, 400, 114, 32))
        self.pushButtonEditShipper.setStyleSheet("background-color: rgb(255, 193, 44);")
        self.pushButtonEditShipper.setObjectName("pushButtonEditShipper")
        self.pushButtonDeleteShipper = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonDeleteShipper.setGeometry(QtCore.QRect(90, 400, 114, 32))
        self.pushButtonDeleteShipper.setStyleSheet("background-color: rgb(253, 70, 70);")
        self.pushButtonDeleteShipper.setObjectName("pushButtonDeleteShipper")
        self.labelError = QtWidgets.QLabel(self.centralwidget)
        self.labelError.setGeometry(QtCore.QRect(340, 520, 421, 21))
        self.labelError.setText("")
        self.labelError.setObjectName("labelError")
        self.pushButtonHome = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonHome.setGeometry(QtCore.QRect(720, 20, 41, 41))
        self.pushButtonHome.setStyleSheet("background-image: url(:/home/baseline_home_black_18dp.png);")
        self.pushButtonHome.setText("")
        self.pushButtonHome.setObjectName("pushButtonHome")
        AddShipper.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddShipper)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        AddShipper.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddShipper)
        self.statusbar.setObjectName("statusbar")
        AddShipper.setStatusBar(self.statusbar)

        self.retranslateUi(AddShipper)
        QtCore.QMetaObject.connectSlotsByName(AddShipper)

    def retranslateUi(self, AddShipper):
        _translate = QtCore.QCoreApplication.translate
        AddShipper.setWindowTitle(_translate("AddShipper", "MainWindow"))
        self.label.setText(_translate("AddShipper", "ADD SHIPPER"))
        self.label_2.setText(_translate("AddShipper", "Shipper Name:"))
        self.label_3.setText(_translate("AddShipper", "Shipper Address:"))
        self.label_4.setText(_translate("AddShipper", "Origin Address:"))
        self.label_5.setText(_translate("AddShipper", "Destination Address:"))
        self.label_6.setText(_translate("AddShipper", "Comments:"))
        self.pushButtonAddShipper.setText(_translate("AddShipper", "Add Shipper"))
        self.pushButtonEditShipper.setText(_translate("AddShipper", "Edit Shipper"))
        self.pushButtonDeleteShipper.setText(_translate("AddShipper", "Delete Shipper"))

import shipper_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddShipper = QtWidgets.QMainWindow()
    ui = Ui_AddShipper()
    ui.setupUi(AddShipper)
    AddShipper.show()
    sys.exit(app.exec_())

